### ISSUE TITLE
probably not really an issue

### ISSUE THREAD

**Issue by rayfield** [brandonio21/download-sweeper#8]
when I try to run download_sweeper i get a SyntaxError:

$ python download_sweeper.py
  File "download_sweeper.py", line 308
    def add_record(self, filePath, moveLocation, moveDate: str):
                                                         ^
(the carat is actually beneath the colon in moveDate:)

dependencies are there.

**Comment by brandonio21** [comment]
I reckon this is because that `moveDate: str` is a feature of Python3 and you are running it with Python2.

Does running with Python3 fix the issue?

**Comment by rayfield** [comment]
thanks. here's what I tried:

$ python3 download_sweeper.py
Traceback (most recent call last):
  File "download_sweeper.py", line 12, in <module>
    import yaml
ImportError: No module named 'yaml'

yaml for Python 2.7 had been installed; so, after Googling that error I did this:

pip install PyYAML
Collecting PyYAML
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 4.2MB/s 
Building wheels for collected packages: PyYAML
  Running setup.py bdist_wheel for PyYAML ... done
  Stored in directory: /home/raphael/.cache/pip/wheels/2c/f7/79/13f3a12cd723892437c0cfbde1230ab4d82947ff7b3839a4fc
Successfully built PyYAML
Installing collected packages: PyYAML
Successfully installed PyYAML-3.11

then same error as before:

$ python3 download_sweeper.py
Traceback (most recent call last):
  File "download_sweeper.py", line 12, in <module>
    import yaml
ImportError: No module named 'yaml'
raphael@SwannUbuntu:~/download-sweeper$ 

I understand this is an issue with Python and various libraries and dependencies but theoretically at least this might help users who are using Ubuntu 16.04 out-of-the-box)

**Comment by rayfield** [comment]
okay, finding similar issues (eg here

https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/590

basically it seems I had to upgrade to pip3 to install and configure everything properly.

so now, "python3 download_sweeper.py" appears to run and complete without incident or output -- unfortunately no files appear to have been moved, or perhaps there something I'm not understanding about how download_sweeper operates.

**Comment by brandonio21** [comment]
Great! Glad you got it working. I think that most of the Python3 features being used are pure syntactic-sugar, so maybe it's worth doing an audit and removing the Python3 specific features. (But at the same time, Python3 is the future!.. maybe I'll choose to do nothing)

Anywho, by default `download_sweeper.py` should move files only if they are 30+ days old. The program should have autogenerated a config file at `$HOME/.config/download-sweeper/config.yaml` that you can inspect to see where files are being put. Maybe this will help you figure out the mystery.

**Comment by rayfield** [comment]
here's what I've got:

~/.config/download-sweeper/records.yaml
which contains:
`{}`

and
~/.config/download-sweeper/config.yaml
which contains:

`archive_directories: []
archive_downloads: true
archive_stale_after: 30d
compress_archives: true
delete_from_purge: true
download_directories: []
download_stale_after: 30d
move_to_all_archive_dirs: true
move_to_all_purge_dirs: true
purge_archives: true
purge_directories: []
purge_stale_after: 1d
`
not really sure why those directories entries are empty (unless they are supposed to be), as the pertinent section of config.yaml is

`# Directory configuraiton settings
download_directories:
        - "/media/whouse/Homies/Downloads/"
archive_directores:
        - "/media/whouse/Homies/.download-archive/"
purge_directores:
        - "/media/whouse/Homies/.download-purge/"
`

**Comment by brandonio21** [comment]
OK. Thanks so much for talking through your process, as you are demonstrating that there are definitely some usability issues. 

By default, `download_sweeper.py` reads its config from `$HOME/.config/download-sweeper/config.yaml`. If that is not present, it creates a new, blank config. That is what it has done for you.

I believe that you have two options that would solve the problem:
You can move your config to the default config location with something like `cp config.yaml $HOME/.config/download-sweeper/config.yaml`

Or

You can tell `download_sweeper.py` to use your config instead of the one in the default location with a commandline flag, ie `python3 download_sweeper.py --config config.yaml`

**Comment by rayfield** [comment]
here is the output after copying config.yam1 to `$HOME/.config/download-sweeper/config.yaml`:
```
 python3 download_sweeper.py
Traceback (most recent call last):
  File "download_sweeper.py", line 483, in <module>
    load_untracked_archives_into_record(sweeperObj, records)
  File "download_sweeper.py", line 455, in load_untracked_archives_into_record
    archivedFiles = sweeper.get_all_file_paths(archiveConfigTranslator)
  File "download_sweeper.py", line 215, in get_all_file_paths
    configTranslator.path_key):
  File "download_sweeper.py", line 286, in get_option_value
    self.config_file_dict[key])
KeyError: 'archive_directories'

and this is what results from `python3 download_sweeper.py --config config.yaml`
python3 download_sweeper.py --config config.yaml
Traceback (most recent call last):
  File "download_sweeper.py", line 478, in <module>
    configMgr = ConfigurationManager(parsed_args.config, parsed_args)
  File "download_sweeper.py", line 240, in __init__
    self.load_config_file()
  File "download_sweeper.py", line 276, in load_config_file
    self.write_default_config_values()
  File "download_sweeper.py", line 269, in write_default_config_values
    with open(self.config_file_path, 'w+') as config_file:
NotADirectoryError: [Errno 20] Not a directory: 'config.yaml/config.yaml'

**Comment by brandonio21** [comment]
I don't know what is going on in the first error.. I'll have to research that.  It definitely seems like `archive_directories` is in your configuration file.


For the second issue, I just looked at the code. Apparently the `--config` flag actually specifies "The location of the configuration directory".. _Who_ designed this thing?

So I guess the proper course of action would be to do `python3 download_sweeper.py --config .`

In theory, you should get the first error though. If you do, go ahead and post your whole `config.yaml`. Seems like there is something wrong

**Comment by rayfield** [comment]
sure enough
```

$ python3 download_sweeper.py --config .
Traceback (most recent call last):
  File "download_sweeper.py", line 483, in <module>
    load_untracked_archives_into_record(sweeperObj, records)
  File "download_sweeper.py", line 455, in load_untracked_archives_into_record
    archivedFiles = sweeper.get_all_file_paths(archiveConfigTranslator)
  File "download_sweeper.py", line 215, in get_all_file_paths
    configTranslator.path_key):
  File "download_sweeper.py", line 286, in get_option_value
    self.config_file_dict[key])
KeyError: 'archive_directories'

```

here is config.yaml:
```

`# Functionality enable settings
archive_downloads:  true
purge_archives:     true
compress_archives:  true
delete_from_purge:  false

# Transfer settings
move_to_all_archive_dirs:   true # If false, will only move to the first archive dir
move_to_all_purge_dirs:     true # If false, will only move to the first purge dir

# Time limit configuration settings
download_stale_after: "30d"
archive_stale_after: "30d"
purge_stale_after: "1d"

# Directory configuraiton settings
download_directories:
        - "/media/whouse/Homies/Downloads/"
archive_directores:
        - "/media/whouse/Homies/.download-archive/"
purge_directores:
        - "/media/whouse/Homies/.download-purge/"

```

**Comment by brandonio21** [comment]
Doh. Seems like there's a spelling error in the default `config.yaml`.

`archive_directores:` should be `archive_directories:`

**Comment by brandonio21** [comment]
@rayfield - So I've gone ahead and made a bunch of changes that should make your (and others) lives easier. If you pull the latest version, you should be able to just run no-problem.

```bash
git pull origin master  # Get latest changes
# Make changes to config.yaml according to your needs
python download_sweeper.py
```

**Comment by rayfield** [comment]
no joy. first I updated, after moving out my config.yaml:

`$ git pull origin master
From https://github.com/brandonio21/download-sweeper
 * branch            master     -> FETCH_HEAD
Updating 1ad8011..8bd52c5
Fast-forward
 README.md           | 10 +++++-----
 config.yaml         |  4 ++--
 download_sweeper.py | 44 +++++++++++++++++++++++++++++---------------
 3 files changed, 36 insertions(+), 22 deletions(-)
`
here's the outputs, first

`$ python3 download_sweeper.py --config .Traceback (most recent call last):
  File "download_sweeper.py", line 492, in <module>
    configMgr = ConfigurationManager(parsed_args.config, parsed_args)
  File "download_sweeper.py", line 249, in __init__
    self.load_config_file()
  File "download_sweeper.py", line 287, in load_config_file
    with open(self.config_file_path, 'r') as openConfigFile:
IsADirectoryError: [Errno 21] Is a directory: '.'
`
then

`$ python3 download_sweeper.py
Traceback (most recent call last):
  File "download_sweeper.py", line 497, in <module>
    load_untracked_archives_into_record(sweeperObj, records)
  File "download_sweeper.py", line 472, in load_untracked_archives_into_record
    archivedFiles)
  File "download_sweeper.py", line 485, in add_unknown_files_to_record
    if not records.record_exists(locationType, path):
  File "download_sweeper.py", line 327, in record_exists
    mov_records = self.records[str(movLocation)]
KeyError: 'archive'
`

also, no files are created in ~/.config/download-sweeper
config.yaml:

> # Functionality enable settings
archive_downloads:  true
purge_archives:     true
compress_archives:  true
delete_from_purge:  false

# Transfer settings
move_to_all_archive_dirs:   true # If false, will only move to the first archive dir
move_to_all_purge_dirs:     true # If false, will only move to the first purge dir

# Time limit configuration settings
download_stale_after: "30d"
archive_stale_after: "30d"
purge_stale_after: "1d"

# Directory configuraiton settings
download_directories:
        - "/media/whouse/Homies/Downloads/"
archive_directories:
        - "/media/whouse/Homies/.download-archive/"
purge_directories:
        - "/media/whouse/Homies/.download-purge/"

**Comment by brandonio21** [comment]
Thanks again for revealing so many issues. I think I pinpointed this and fixed it in https://github.com/brandonio21/download-sweeper/commit/a971af356b012c2b27d5889a4ccd35582ea11d3f

**Comment by rayfield** [comment]
okay, now running
`python3 download_sweeper.py
`
in the download-sweeper directory completes without issues. however, no files have been moved, though there are quite a few files in there well over 30 days old (the reason I'm interested in d-s is because there's stuff been in /Downloads for 7-8 years).

a question: I have one or two subdirectories in /Downloads which I would *not* want moved or archived. does download-sweeper operate recursively by default?

**Comment by brandonio21** [comment]
Interesting. One thing to note is that d-s compares time by _access_, not by _modification_ nor _creation_. Unfortunately, this makes things a little confusing. For instance, on my system, something _accesses_ all subfolders in my Downloads folder daily.. but I'm not quite sure what is accessing them.

Maybe your files' access times are more recent than you thought? Try `stat`ing them.

And yes, d-s is recursive by default. There should definitely be some sort of option to prevent this behavior, though. Atleast, there should definitely be a blacklist feature.
